[versions]
guava = "33.5.0-jre"
jgit = "7.5.0.202512021534-r"
junit-jupiter = "6.0.2"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }